### ISSUE TITLE
Error on saving config

### ISSUE THREAD

**Issue by TimVroom** [ICEPAY/Magento#13]
When I save the configs in the backend of magento we get the following error:

An error occurred while saving this configuration: Notice: Trying to get property of non-object in /app/code/core/Mage/Adminhtml/Model/Config/Data.php on line 135.

This error occurs on multiple config values:
- icecore/iceadvanced/webservice_data
- icecore/iceadvanced/active
- icecore/paymentmethod/pm_*_title
- icecore/paymentmethod/pm_*_active

The \* is for all the available payment methods.

Also this will only occur when error reporting is set to trigger on NOTICE errors.

**Comment by tsygankov** [comment]
Hi Tim,

Thank you very much for your feedback and donating your time for this project!

Can you please specify the Magento version you were using? We've tried to reproduce the issue using 1.9.2.4 version of Magento and the described above problem does not appear. We will repeat testing using other Magento versions.

The problem may be related to a bug in Magento 1.7.0.2
http://www.magentocommerce.com/bug-tracking/issue?issue=14217

Unfortunately, the Magento bugtracker link is not working at the moment, however you can find the same bug description [here.](http://support.createhosting.co.nz/knowledgebase.php?action=displayarticle&id=69 )

**Comment by TimVroom** [comment]
Hi Tsygankov,

It is indeed a Magento 1.7.0.2 installation. So not really an issue when its fully upgraded, but those older installs will still suffer from the error.
